apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: processing
  annotations:
    eks.amazonaws.com/role-arn: ${SPARK_ROLE_ARN}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role
  namespace: processing
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: processing
roleRef:
  kind: ClusterRole
  name: spark-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-spark-role
  namespace: processing
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: orchestrator
roleRef:
  kind: ClusterRole
  name: spark-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-spark-role-view
  namespace: processing
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: orchestrator
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role-edit
  namespace: processing
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: processing
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-worker-cr
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
rules:
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications
    verbs:
      - "*"
  - apiGroups:
      - ""
    verbs:
      - "*"
    resources:
      - pods
      - pods/log
      - events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-spark-worker-cr
  namespace: processing
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: orchestrator
roleRef:
  kind: ClusterRole
  name: spark-worker-cr
  apiGroup: rbac.authorization.k8s.io
