apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgres-credentials
  namespace: orchestrator
data:
  connection: ${CONNECTION_STRING}
  db_host: ${AIRFLOW_DB_HOST}
  db_port: ${AIRFLOW_DB_PORT}
  db_admin_user: ${AIRFLOW_DB_ADMIN_USER}
  db_admin_name: ${AIRFLOW_DB_ADMIN_DB}
  db_user: ${AIRFLOW_DB_USER}
  db_user_password: ${AIRFLOW_DB_PASSWORD}
  db_name: ${AIRFLOW_DB_NAME}
  pgpassword: ${AIRFLOW_DB_ADMIN_PASSWORD}