apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: ${GIT_SYNC_USERNAME}
  GIT_SYNC_PASSWORD: ${GIT_SYNC_PASSWORD}
  GITSYNC_USERNAME: ${GIT_SYNC_USERNAME}
  GITSYNC_PASSWORD: ${GIT_SYNC_PASSWORD}
