{
 "title": "K8S PODs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage by POD ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node_name=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "[USED] {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "[REQUESTED] {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage by POD ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node_name=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "[USED] {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "[REQUESTED] {{pod}}"
    }
   ]
  },
  {
   "title": "Detalhes dos PODs",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  }
 ]
}