{
 "title": "K8S Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Requested ($node)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", node=~\"$node\"} * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Requested ($node)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", node=~\"$node\"} * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk Usage ($node)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_avail_bytes{mountpoint=\"/\", node=~\"$node\"})/sum(node_filesystem_size_bytes{mountpoint=\"/\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes by Node Group",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "kube_node_info==1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster CPU Usage ($node)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", namespace!=\"\", node_name=~\"$node\"}[15m]) * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage ($node)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\", namespace!=\"\", node_name=~\"$node\"} * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info==1)" }
   ]
  },
  {
   "title": "Nodes with DiskPressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"}==1)"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==0)"
    }
   ]
  },
  { "title": "Detalhado", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Requested by Node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"} * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (node)"
    }
   ]
  },
  {
   "title": "Memory Requested by Node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"} * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (node)"
    }
   ]
  },
  {
   "title": "Number of Nodes History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count(kube_node_info==1)", "legendFormat": "Nodes" }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", namespace!=\"\"}[15m]) * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (node_name)"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\", namespace!=\"\"} * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (node_name)"
    }
   ]
  },
  {
   "title": "Detalhado por POD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "PODs Running by Nodes",
     "type": "table",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "kube_pod_info{node=~\"$node\"} * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)"
      }
     ]
    }
   ]
  }
 ]
}