apiVersion: v1
kind: Secret
metadata:
  name: ${REPO_NAME}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${REPO_URL}
  username: "${REPO_USERNAME}"
  password: "${REPO_PASSWORD}"
  insecure: "true"
