apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-database-user-job
  namespace: orchestrator
spec:
  template:
    spec:
      containers:
      - name: user-database-creator
        image: ${CONTAINER_IMAGE}
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-credentials
              key: pgpassword
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-credentials
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-credentials
              key: db_port
        - name: DB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-credentials
              key: db_admin_user
        - name: DB_ADMIN_NAME
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-credentials
              key: db_admin_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-credentials
              key: db_user
        - name: DB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-credentials
              key: db_user_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-credentials
              key: db_name
        volumeMounts:
        - name: airflow-db-secret-volume
          mountPath: /secrets
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: airflow-db-secret-volume
        secret:
          secretName: airflow-postgres-credentials
